version: '2.4'
services:
  badseed:
    build: .
    ports:
      - 2200:5000
    read_only: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
