version: '3.3'
services:
  wyze_guy:
    build: .
    ports:
      - 4444:4444
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
